name : Generate SBOM
on:
    workflow_run:
      workflows: ["Build Binary"]
      types: completed
      
          
jobs:
    build: 
        name: Generate SBOM
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Echo-Test
              run: |
               echo "Test"
        